# Generated by Django 3.2.7 on 2021-10-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='std',
            field=models.IntegerField(default=0),
        ),
    ]
