# Generated by Django 3.2.7 on 2021-10-05 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_student_std'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collegeId', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=50)),
                ('college_address', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.RenameField(
            model_name='student',
            old_name='address',
            new_name='student_address',
        ),
        migrations.AddField(
            model_name='student',
            name='college',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='my_app.college'),
        ),
    ]
